export const TYPE = 'TYPE';

const Types = {
    TYPE:'TYPE',
    LOGIN_USER:'LOGIN_USER',
    GET_USER:'GET_USER',
    SET_USER_LOGGED_IN:'SET_USER_LOGGED_IN',
    SET_USER:'SET_USER',
    SET_USER_ERROR:'SET_USER_ERROR',
    LOG_OUT:'LOG_OUT',
    LOADING_ON:'LOADING_ON',
    LOADING_OFF:'LOADING_OFF',
    GET_CATEGORY:'GET_CATEGORY',
    ERROR_CATEGORY:'ERROR_CATEGORY',

    GET_PRODUCT:'GET_PRODUCT',
    SET_PRODUCT:'SET_PRODUCT',
    
    ERROR_PRODUCT:'ERROR_PRODUCT',
    GET_ABOUTUSIMAGE:'GET_ABOUTUSIMAGE',
    SET_ABOUTUSIMAGE:'SET_ABOUTUSIMAGE',
    
    ERROR_ABOUTUSIMAGE:'ERROR_ABOUTUSIMAGE',
    GET_IMAGE:'GET_IMAGE',
    SET_IMAGE:'SET_IMAGE',
    
    ERROR_IMAGE:'ERROR_IMAGE',

   



}

export default Types